# WARNING - Generated by {fusen} from dev/flat_downsampling.qmd: do not edit by hand # nolint: line_length_linter.

library(spatstat.random)
library(spatstat.geom)

make_marked <- function(n = 3000) {
  X <- rpoispp(n)
  marks(X) <- factor(sample(c("T", "B", "Tum"), npoints(X), replace = TRUE))
  X
}

test_that("wrapper dispatches and handles lists reproducibly", {
  Xs <- list(a = rpoispp(1000), b = rpoispp(2000))
  set.seed(7); Y1 <- downsample(Xs, method = "uniform", n_target = c(100, 200))
  set.seed(7); Y2 <- downsample(Xs, method = "uniform", n_target = c(100, 200))
  expect_named(Y1, c("a", "b"))
  expect_equal(unname(sapply(Y1, npoints)), c(100, 200))
  expect_identical(Y1$a$x, Y2$a$x)
  expect_equal(attr(downsample(Xs$a, "kde", prop = 0.1), "downsample")$method, "kde")
  expect_error(downsample(list(1, 2), n_target = 10), "list of ppp")
  expect_error(downsample(Xs, n_target = c(1, 2, 3)), "length")
})

test_that("marks and by_marks select and downsample each type", {
  set.seed(8)
  X <- rpoispp(5000)
  marks(X) <- factor(sample(c("neo", "stroma", "imm"), npoints(X),
                            replace = TRUE, prob = c(.6, .3, .1)))
  Y <- downsample(X, "uniform", n_target = 300, marks = c("neo", "stroma"),
                  by_marks = TRUE)
  expect_equal(as.vector(table(marks(Y))), c(300, 300))
  expect_equal(levels(marks(Y)), c("neo", "stroma"))
  expect_true(attr(Y, "downsample")$by_marks)
  # all kept points are points of X
  expect_true(all(paste(Y$x, Y$y) %in% paste(X$x, X$y)))

  # types smaller than n_target are kept whole
  Z <- downsample(X, "uniform", n_target = 1e6, by_marks = TRUE)
  expect_equal(npoints(Z), npoints(X))

  # prop per type, KDE per type
  P <- downsample(X, "kde", prop = 0.1, by_marks = TRUE)
  expect_equal(as.vector(table(marks(P))),
               round(0.1 * as.vector(table(marks(X)))))

  # marks only, without by_marks: total target
  Q <- downsample(X, "uniform", n_target = 200, marks = "imm")
  expect_equal(npoints(Q), 200)

  expect_error(downsample(X, "window", prop = .5, by_marks = TRUE), "window")
  expect_error(downsample(X, marks = "tumor", prop = .5), "not found")
  expect_error(downsample(unmark(X), prop = .5, by_marks = TRUE), "factor")
})
