# WARNING - Generated by {fusen} from dev/flat_downsampling.qmd: do not edit by hand # nolint: line_length_linter.

library(spatstat.random)
library(spatstat.geom)

make_marked <- function(n = 3000) {
  X <- rpoispp(n)
  marks(X) <- factor(sample(c("T", "B", "Tum"), npoints(X), replace = TRUE))
  X
}

test_that("target resolution works", {
  set.seed(1)
  X <- rpoispp(1000)
  expect_error(downsample_uniform(X), "exactly one")
  expect_error(downsample_uniform(X, n_target = 10, prop = 0.1), "exactly one")
  expect_error(downsample_uniform(X, prop = 1.5), "prop")
  expect_equal(npoints(downsample_uniform(X, n_target = 1e6)), npoints(X))
})

test_that("uniform keeps exact n and marks", {
  set.seed(2)
  X <- make_marked()
  Y <- downsample_uniform(X, n_target = 500)
  expect_equal(npoints(Y), 500)
  expect_true(is.factor(marks(Y)))
  expect_equal(attr(Y, "downsample")$method, "uniform")
  Z <- downsample_uniform(X, prop = 0.2, exact = FALSE)
  expect_true(abs(npoints(Z) - 0.2 * npoints(X)) < 0.05 * npoints(X))
})

test_that("uniform thinning preserves L-cross (approximately)", {
  set.seed(3)
  X <- rMatClust(30, 0.04, 150)
  marks(X) <- factor(sample(c("a", "b"), npoints(X), replace = TRUE))
  r <- seq(0, 0.1, length.out = 21)
  L0 <- spatstat.explore::Lcross(X, "a", "b", r = r, correction = "border")$border
  L1 <- spatstat.explore::Lcross(downsample_uniform(X, prop = 0.3),
                                 "a", "b", r = r, correction = "border")$border
  expect_lt(max(abs(L1 - L0)[-1]), 0.02)
})
