# WARNING - Generated by {fusen} from dev/flat_read_data.qmd: do not edit by hand # nolint: line_length_linter.

library(spatstat.geom)

sim_cells <- function(n = 400, size = 320) {
  data.frame(
    x = runif(n, 0, size), y = runif(n, 0, size),
    mark = factor(sample(c("tumor", "stroma"), n, replace = TRUE))
  )
}

write_mask <- function(m, ...) {
  f <- tempfile(fileext = ".png")
  png::writePNG(m, f, ...)
  f
}

test_that("read_cells_h5ad and ann2ppp read h5ad and h5ad.gz", {
  skip_if_not_installed("anndataR")
  skip_if_not_installed("rhdf5")
  set.seed(4)
  n <- 30
  obs <- data.frame(type = sample(c("tumor", "stroma"), n, replace = TRUE),
                    cx = runif(n, 0, 100), cy = runif(n, 0, 100),
                    row.names = paste0("cell", seq_len(n)))
  ad <- anndataR::AnnData(
    obs = obs,
    var = data.frame(row.names = "g1"),
    X = matrix(0, n, 1),
    obsm = list(spatial = as.matrix(obs[, c("cx", "cy")]))
  )
  f <- tempfile(fileext = ".h5ad")
  anndataR::write_h5ad(ad, f)

  cells <- read_cells_h5ad(f)
  expect_equal(nrow(cells), n)
  expect_equal(cells$x, obs$cx)
  expect_equal(as.character(cells$mark), obs$type)

  expect_equal(read_cells_h5ad(f, coords_cols = c("cx", "cy"))$y, obs$cy)
  expect_error(read_cells_h5ad(f, marks_col = "celltype"), "not found")
  expect_error(read_cells_h5ad(f, spatial_key = "X_umap"), "obsm")

  # gzip-compressed file
  gz <- paste0(f, ".gz")
  con <- gzfile(gz, "wb"); writeBin(readBin(f, "raw", file.size(f)), con)
  close(con)
  pp <- ann2ppp(gz)
  expect_s3_class(pp, "ppp")
  expect_equal(npoints(pp), n)

  # uncompressed HDF5 with a ".gz" name (as in the TCGA files)
  fake_gz <- paste0(tempfile(), ".h5ad.gz")
  file.copy(f, fake_gz)
  expect_equal(nrow(read_cells_h5ad(fake_gz)), n)
  expect_null(marks(ann2ppp(f, marks_col = NULL)))
})

test_that("the example TCGA h5ad is read with the right scale", {
  skip_if_not_installed("anndataR")
  f <- system.file("extdata", "tcga_tiny.h5ad", package = "SpaFun")
  mask <- system.file("extdata", "tcga_tiny_mask.png", package = "SpaFun")
  skip_if(!nzchar(f) || !nzchar(mask), "example files not installed")
  cells <- read_cells_h5ad(f)
  expect_gt(nrow(cells), 100)
  expect_true("neoplastic" %in% levels(cells$mark))
  pp <- suppressMessages(ann2ppp(f, mask = mask, magnif = 40))
  # with the right scale and orientation almost no cell falls outside
  expect_lt(attr(pp, "n_removed")[["outside_window"]], 0.01 * nrow(cells))
})

test_that("read_cells_h5ad checks the path", {
  skip_if_not_installed("anndataR")
  expect_error(read_cells_h5ad("does_not_exist.h5ad"), "existing file")
})
