# WARNING - Generated by {fusen} from dev/flat_downsampling.qmd: do not edit by hand # nolint: line_length_linter.

library(spatstat.random)
library(spatstat.geom)

make_marked <- function(n = 3000) {
  X <- rpoispp(n)
  marks(X) <- factor(sample(c("T", "B", "Tum"), npoints(X), replace = TRUE))
  X
}

test_that("KDE downsampling returns n_target points", {
  set.seed(4)
  X <- rMatClust(20, 0.05, 100)
  Y <- downsample_KDE(X, n_target = 300)
  expect_equal(npoints(Y), 300)
  expect_true(is.numeric(attr(Y, "downsample")$sigma))
  expect_equal(npoints(downsample_KDE(X, n_target = 300, sigma = 0.05)), 300)
})
