# WARNING - Generated by {fusen} from dev/flat_read_data.qmd: do not edit by hand # nolint: line_length_linter.

library(spatstat.geom)

sim_cells <- function(n = 400, size = 320) {
  data.frame(
    x = runif(n, 0, size), y = runif(n, 0, size),
    mark = factor(sample(c("tumor", "stroma"), n, replace = TRUE))
  )
}

write_mask <- function(m, ...) {
  f <- tempfile(fileext = ".png")
  png::writePNG(m, f, ...)
  f
}

test_that("cells2ppp: bounding box, marks and column checks", {
  set.seed(1)
  cells <- sim_cells()
  pp <- cells2ppp(cells)
  expect_s3_class(pp, "ppp")
  expect_equal(npoints(pp), nrow(cells))
  expect_equal(levels(marks(pp)), levels(cells$mark))
  expect_equal(unname(attr(pp, "n_removed")), c(0, 0))

  expect_null(marks(cells2ppp(cells, marks_col = NULL)))
  expect_error(cells2ppp(cells, marks_col = "type"), "type")
  expect_error(cells2ppp(as.matrix(cells[, 1:2])), "data.frame")

  names(cells)[1:2] <- c("cx", "cy")
  expect_equal(npoints(cells2ppp(cells, x_col = "cx", y_col = "cy")), 400)
})

test_that("cells2ppp: missing coordinates are removed", {
  set.seed(2)
  cells <- sim_cells(50)
  cells$x[1:3] <- NA
  expect_message(pp <- cells2ppp(cells), "3 cell")
  expect_equal(npoints(pp), 47)
  expect_equal(attr(pp, "n_removed")[["missing_coords"]], 3)
})

test_that("cells2ppp: PNG mask is scaled and oriented correctly", {
  # 10 x 10 thumbnail, tissue only in the TOP-LEFT quarter (rows 1-5 = top)
  m <- matrix(0, 10, 10); m[1:5, 1:5] <- 1
  f <- write_mask(m)
  cells <- data.frame(x = c(10, 300, 10), y = c(10, 10, 300),
                      mark = factor(c("a", "b", "a")))
  # magnif 40 / thumb 1.25 = 32 units per pixel -> window 320 x 320
  expect_message(pp <- cells2ppp(cells, mask = f, magnif = 40), "2 of 3")
  expect_equal(Frame(pp)$xrange, c(0, 320))
  expect_equal(area(Window(pp)), 160^2)
  # only the cell near the origin (top-left in image coordinates) is kept
  expect_equal(c(pp$x, pp$y), c(10, 10))
  expect_equal(attr(pp, "n_removed")[["outside_window"]], 2)

  # same result with mask_scale
  pp2 <- suppressMessages(cells2ppp(cells, mask = f, mask_scale = 32))
  expect_equal(area(Window(pp2)), area(Window(pp)))
})

test_that("cells2ppp: RGB/alpha masks, threshold and invert", {
  m <- matrix(0, 8, 8); m[, 1:4] <- 1
  rgba <- array(1, c(8, 8, 4)); rgba[, , 1:3] <- m
  f <- write_mask(rgba)
  cells <- data.frame(x = c(1, 7), y = c(4, 4), mark = factor(c("a", "b")))
  pp <- suppressMessages(cells2ppp(cells, mask = f, mask_scale = 1))
  expect_equal(area(Window(pp)), 32)
  ppi <- suppressMessages(cells2ppp(cells, mask = f, mask_scale = 1,
                                    invert = TRUE))
  expect_equal(ppi$x, 7)
  expect_error(cells2ppp(cells, mask = write_mask(matrix(0, 4, 4)),
                         mask_scale = 1), "empty")
})

test_that("cells2ppp: owin mask and argument checks", {
  set.seed(3)
  cells <- sim_cells(200, size = 1)
  W <- disc(0.5, c(0.5, 0.5))
  pp <- suppressMessages(cells2ppp(cells, mask = W))
  expect_true(all(inside.owin(pp$x, pp$y, W)))
  # owin in thumbnail units rescaled
  pp10 <- suppressMessages(cells2ppp(cells, mask = owin(c(0, 0.1), c(0, 0.1)),
                                     mask_scale = 10))
  expect_equal(npoints(pp10), nrow(cells))

  f <- write_mask(matrix(1, 4, 4))
  expect_error(cells2ppp(cells, mask = f), "mask_scale")
  expect_error(cells2ppp(cells, mask = f, mask_scale = 2, magnif = 40),
               "not both")
  expect_error(cells2ppp(cells, mask = f, magnif = "40x"), "single positive")
  expect_error(cells2ppp(cells, mask = "nope.png", mask_scale = 1), "not found")
  expect_error(cells2ppp(cells, mask = 1), "PNG")
})
