# WARNING - Generated by {fusen} from dev/flat_downsampling.qmd: do not edit by hand # nolint: line_length_linter.

library(spatstat.random)
library(spatstat.geom)

make_marked <- function(n = 3000) {
  X <- rpoispp(n)
  marks(X) <- factor(sample(c("T", "B", "Tum"), npoints(X), replace = TRUE))
  X
}

test_that("window downsampling keeps all points in the new window", {
  set.seed(5)
  X <- make_marked()
  Y <- downsample_window(X, prop = 0.25)
  expect_gte(npoints(Y), round(0.25 * npoints(X)))
  expect_true(all(inside.owin(Y$x, Y$y, Window(Y))))
  # every original point inside the new window has been kept
  expect_equal(sum(inside.owin(X$x, X$y, Window(Y))), npoints(Y))
  expect_s3_class(attr(Y, "downsample")$tiles, "tess")
})

test_that("window downsampling works on irregular windows", {
  set.seed(6)
  X <- rpoispp(2000, win = disc(1))
  Y <- downsample_window(X, n_target = 400, tile_size = 0.3)
  expect_gte(npoints(Y), 400)
  expect_true(is.subset.owin(Window(Y), Window(X)))
})
