# WARNING - Generated by {fusen} from dev/flat_read_data.qmd: do not edit by hand # nolint: line_length_linter.

#' Read an h5ad file as a point pattern
#'
#' Convenience wrapper: [read_cells_h5ad()] followed by [cells2ppp()].
#'
#' @inheritParams read_cells_h5ad
#' @inheritParams cells2ppp
#' @param ... Further arguments passed to [cells2ppp()] (`threshold`,
#'   `invert`).
#'
#' @return A `ppp` object, see [cells2ppp()].
#' @export
#' @examples
#' f    <- system.file("extdata", "tcga_tiny.h5ad", package = "SpaFun")
#' mask <- system.file("extdata", "tcga_tiny_mask.png", package = "SpaFun")
#' if (nzchar(f) && requireNamespace("anndataR", quietly = TRUE)) {
#'   # the mask covers the whole slide, the tiny file only a small square of it
#'   pp <- ann2ppp(f, mask = mask, magnif = 40, thumb_mag = 1.25,
#'                 marks_col = "type")
#'   pp
#' }
ann2ppp <- function(data_path, mask = NULL, mask_scale = NULL,
                    magnif = NULL, thumb_mag = 1.25, marks_col = "type",
                    spatial_key = "spatial", coords_cols = NULL, ...) {
  cells <- read_cells_h5ad(data_path, marks_col = marks_col,
                           spatial_key = spatial_key,
                           coords_cols = coords_cols)
  cells2ppp(cells, mask = mask, mask_scale = mask_scale, magnif = magnif,
            thumb_mag = thumb_mag,
            marks_col = if (is.null(marks_col)) NULL else "mark", ...)
}
