# WARNING - Generated by {fusen} from dev/flat_read_data.qmd: do not edit by hand # nolint: line_length_linter.

#' Build a point pattern from a table of cells
#'
#' Turns a table of cell centroids into a `spatstat` point pattern. The
#' window is either the bounding box of the cells or a tissue mask, given as
#' a PNG file (a thumbnail of the slide) or as an `owin`.
#'
#' Coordinates and mask must use the same orientation: with a PNG the first
#' pixel row is the top of the image, as with centroids in image coordinates
#' (y growing downwards).
#'
#' @param cells A `data.frame` with the coordinates and, optionally, the
#'   labels of the cells, e.g. the output of [read_cells_h5ad()].
#' @param mask Optional tissue mask: path to a PNG file or an `owin`. If
#'   `NULL` the window is the bounding box of the cells.
#' @param mask_scale Number of coordinate units per mask pixel, e.g. `32`
#'   for coordinates at 40x and a thumbnail at 1.25x. For an `owin`, it is
#'   used to rescale it (`NULL` means no rescaling).
#' @param magnif,thumb_mag Shortcut for `mask_scale = magnif / thumb_mag`:
#'   magnification of the coordinates (e.g. 20 or 40) and of the mask
#'   thumbnail. Use either these or `mask_scale`.
#' @param threshold Pixels with intensity above `threshold` (0-1 scale,
#'   averaged over colour channels) are tissue.
#' @param invert If `TRUE`, tissue is the pixels *below* `threshold`.
#' @param x_col,y_col,marks_col Column names in `cells`. Set `marks_col` to
#'   `NULL` for an unmarked pattern.
#'
#' @return A `ppp` object. Cells outside the window or with missing
#'   coordinates are removed (with a message); their number is stored in
#'   the attribute `"n_removed"`.
#' @export
#' @examples
#' set.seed(1)
#' cells <- data.frame(
#'   x = runif(500, 0, 320), y = runif(500, 0, 320),
#'   mark = factor(sample(c("tumor", "stroma"), 500, replace = TRUE))
#' )
#'
#' # bounding-box window
#' pp <- cells2ppp(cells)
#'
#' # tissue mask: 10 x 10 pixel PNG, each pixel = 32 units
#' m <- matrix(0, 10, 10); m[2:9, 2:9] <- 1
#' f <- tempfile(fileext = ".png"); png::writePNG(m, f)
#' pp <- cells2ppp(cells, mask = f, magnif = 40, thumb_mag = 1.25)
#' attr(pp, "n_removed")
cells2ppp <- function(cells, mask = NULL, mask_scale = NULL,
                      magnif = NULL, thumb_mag = 1.25,
                      threshold = 0.5, invert = FALSE,
                      x_col = "x", y_col = "y", marks_col = "mark") {
  if (!is.data.frame(cells)) {
    stop("`cells` must be a data.frame.", call. = FALSE)
  }
  needed <- c(x_col, y_col, marks_col)
  missing_cols <- setdiff(needed, names(cells))
  if (length(missing_cols) > 0) {
    stop("Column(s) not found in `cells`: ",
         paste(missing_cols, collapse = ", "), call. = FALSE)
  }

  x <- as.numeric(cells[[x_col]])
  y <- as.numeric(cells[[y_col]])
  marks <- if (is.null(marks_col)) NULL else as.factor(cells[[marks_col]])

  # 1. drop cells with missing coordinates
  ok <- is.finite(x) & is.finite(y)
  n_na <- sum(!ok)
  if (n_na > 0) {
    message(n_na, " cell(s) with missing coordinates removed.")
    x <- x[ok]; y <- y[ok]
    if (!is.null(marks)) marks <- marks[ok]
  }
  if (length(x) == 0) stop("No cells with valid coordinates.", call. = FALSE)

  # 2. window
  scale <- .resolve_mask_scale(mask, mask_scale, magnif, thumb_mag)
  if (is.null(mask)) {
    win <- spatstat.geom::owin(range(x), range(y))
  } else if (spatstat.geom::is.owin(mask)) {
    win <- if (is.null(scale)) mask else
      spatstat.geom::affine(mask, mat = diag(c(scale, scale)))
  } else if (is.character(mask) && length(mask) == 1) {
    win <- .png2owin(mask, scale, threshold, invert)
  } else {
    stop("`mask` must be NULL, the path of a PNG file or an owin.",
         call. = FALSE)
  }

  # 3. drop cells outside the window
  inside <- spatstat.geom::inside.owin(x, y, win)
  n_out <- sum(!inside)
  if (n_out > 0) {
    message(n_out, " of ", length(x), " cell(s) (",
            format(100 * n_out / length(x), digits = 2),
            "%) outside the window removed.")
    x <- x[inside]; y <- y[inside]
    if (!is.null(marks)) marks <- marks[inside]
  }

  pp <- spatstat.geom::ppp(x, y, window = win, marks = marks, check = FALSE)
  attr(pp, "n_removed") <- c(missing_coords = n_na, outside_window = n_out)
  pp
}
