# WARNING - Generated by {fusen} from dev/flat_downsampling.qmd: do not edit by hand # nolint: line_length_linter.

#' Internal helpers for downsampling
#' @noRd
.downsample_marks <- function(pp, fun, method, n_target, prop, marks, by_marks,
                              ...) {
  .check_ppp(pp)
  if (!is.null(marks) || by_marks) {
    m <- spatstat.geom::marks(pp)
    if (!is.factor(m)) {
      stop("`marks` and `by_marks` need a pattern with factor marks.",
           call. = FALSE)
    }
  }
  if (!is.null(marks)) {
    missing_lev <- setdiff(marks, levels(m))
    if (length(missing_lev) > 0) {
      stop("Mark(s) not found: ", paste(missing_lev, collapse = ", "),
           ". Available: ", paste(levels(m), collapse = ", "), call. = FALSE)
    }
    pp <- pp[m %in% marks]
    spatstat.geom::marks(pp) <- factor(spatstat.geom::marks(pp),
                                       levels = marks)
  }
  if (!by_marks) return(fun(pp, n_target = n_target, prop = prop, ...))

  m <- spatstat.geom::marks(pp)
  n_orig <- spatstat.geom::npoints(pp)
  keep <- logical(n_orig)
  for (lev in levels(m)) {
    idx <- which(m == lev)
    if (length(idx) == 0) next
    # carry the original indices as marks, to map the kept points back
    sub <- spatstat.geom::setmarks(pp[idx], idx)
    sub_n <- if (is.null(n_target)) NULL else min(n_target, length(idx))
    res <- fun(sub, n_target = sub_n, prop = prop, ...)
    keep[spatstat.geom::marks(res)] <- TRUE
  }
  .tag(pp[keep], method, n_orig, by_marks = TRUE,
       n_kept_by_mark = table(spatstat.geom::marks(pp)[keep]))
}

.check_ppp <- function(pp) {
  if (!spatstat.geom::is.ppp(pp)) {
    stop("`pp` must be a ppp object.", call. = FALSE)
  }
  invisible(TRUE)
}

.resolve_target <- function(n, n_target, prop) {
  if (is.null(n_target) == is.null(prop)) {
    stop("Specify exactly one of `n_target` and `prop`.", call. = FALSE)
  }
  if (!is.null(prop)) {
    if (!is.numeric(prop) || length(prop) != 1 || prop <= 0 || prop > 1) {
      stop("`prop` must be a single number in (0, 1].", call. = FALSE)
    }
    n_target <- round(prop * n)
  }
  if (!is.numeric(n_target) || length(n_target) != 1 || n_target < 1) {
    stop("`n_target` must be a single positive number.", call. = FALSE)
  }
  as.integer(min(n_target, n))
}

.recycle_arg <- function(x, n, name) {
  if (is.null(x)) return(vector("list", n))
  if (length(x) == 1) return(rep(list(x), n))
  if (length(x) == n) return(as.list(x))
  stop("`", name, "` must have length 1 or the same length as `pp`.",
       call. = FALSE)
}

.tag <- function(out, method, n_orig, ...) {
  attr(out, "downsample") <- c(
    list(method = method, n_orig = n_orig,
         n_kept = spatstat.geom::npoints(out)),
    list(...)
  )
  out
}
