# WARNING - Generated by {fusen} from dev/flat_downsampling.qmd: do not edit by hand # nolint: line_length_linter.

#' Uniform random downsampling
#'
#' Keeps a random subset of points, each point with the same probability.
#' Independent thinning leaves the K and L functions (including the
#' cross-type ones) unchanged, so it is the method to use before `Lcross`.
#'
#' @inheritParams downsample
#' @param exact If `TRUE` (default) keeps exactly `n_target` points (simple
#'   random sampling without replacement). If `FALSE` uses independent
#'   thinning ([spatstat.random::rthin()]): the number of kept points is
#'   random, with expected value `n_target`.
#'
#' @return A `ppp` with attribute `"downsample"`.
#' @export
#' @examples
#' library(spatstat.random)
#' set.seed(1)
#' X <- rpoispp(2000)
#' spatstat.geom::npoints(downsample_uniform(X, n_target = 300))
downsample_uniform <- function(pp, n_target = NULL, prop = NULL, exact = TRUE) {
  .check_ppp(pp)
  n <- spatstat.geom::npoints(pp)
  tgt <- .resolve_target(n, n_target, prop)
  if (tgt >= n) return(.tag(pp, "uniform", n))

  if (exact) {
    out <- pp[sort(sample.int(n, tgt))]
  } else {
    out <- spatstat.random::rthin(pp, P = tgt / n)
  }
  .tag(out, "uniform", n)
}
