# WARNING - Generated by {fusen} from dev/flat_downsampling.qmd: do not edit by hand # nolint: line_length_linter.

#' Inverse-density (KDE) downsampling
#'
#' Samples points with probability proportional to `1 / density`, where the
#' density is a Gaussian kernel estimate. Points in sparse areas are kept
#' more often, so the result is closer to a homogeneous pattern.
#'
#' **Warning:** this changes the second-order structure (K, L, pair
#' correlation) of the pattern and reduces the clustering you would measure.
#' Use it for visualisation or for methods that need even coverage, not
#' before estimating `Lcross`; use [downsample_uniform()] instead.
#'
#' @inheritParams downsample
#' @param sigma Kernel bandwidth. Either a number or a function that takes a
#'   `ppp` and returns a bandwidth. Default [spatstat.explore::bw.scott()],
#'   which is fast on large patterns.
#' @param dimyx Resolution of the pixel grid used for the density estimate
#'   (passed to [spatstat.explore::density.ppp()]). The density is computed
#'   on the grid and looked up at the points, which keeps the cost almost
#'   independent of the number of points.
#' @param ... Further arguments passed to [spatstat.explore::density.ppp()].
#'
#' @return A `ppp` with attribute `"downsample"`.
#' @export
#' @examples
#' library(spatstat.random)
#' set.seed(1)
#' X <- rMatClust(20, 0.05, 100)
#' Y <- downsample_KDE(X, prop = 0.2)
#' spatstat.geom::npoints(Y)
downsample_KDE <- function(pp, n_target = NULL, prop = NULL,
                           sigma = spatstat.explore::bw.scott,
                           dimyx = 256, ...) {
  .check_ppp(pp)
  n <- spatstat.geom::npoints(pp)
  tgt <- .resolve_target(n, n_target, prop)
  if (tgt >= n) return(.tag(pp, "kde", n))

  if (is.function(sigma)) sigma <- sigma(pp)
  # density on a pixel grid (FFT, fast), then looked up at the points:
  # at = "points" is quadratic in n and too slow for large patterns
  dens_im <- spatstat.explore::density.ppp(
    spatstat.geom::unmark(pp), sigma = sigma, dimyx = dimyx, ...
  )
  dens <- spatstat.geom::safelookup(dens_im, pp, warn = FALSE)
  dens[!is.finite(dens) | dens <= 0] <- min(dens[dens > 0 & is.finite(dens)])
  w <- 1 / dens

  # weighted sampling without replacement (Efraimidis-Spirakis): same law as
  # sample.int(n, tgt, prob = w) but O(n log n) instead of O(n * tgt)
  keys <- stats::rexp(n) / w
  out <- pp[sort(order(keys)[seq_len(tgt)])]
  .tag(out, "kde", n, sigma = sigma)
}
