# WARNING - Generated by {fusen} from dev/flat_downsampling.qmd: do not edit by hand # nolint: line_length_linter.

#' Downsample a spatial point pattern
#'
#' Wrapper that reduces the number of points of one or more point patterns
#' with the chosen method. When `pp` is a list of patterns, samples are
#' processed in parallel with `future.apply` (set the backend with
#' `future::plan()`); results are reproducible after `set.seed()`.
#'
#' Methods:
#' - `"uniform"`: random thinning, see [downsample_uniform()]. Leaves K and L
#'   functions unchanged: the recommended choice before computing `Lcross`.
#' - `"kde"`: inverse-density sampling, see [downsample_KDE()]. Makes the
#'   pattern more homogeneous: do not use it to estimate K or L.
#' - `"window"`: keeps all points inside random tiles, see
#'   [downsample_window()]. Local structure is intact, observed area shrinks.
#'
#' @param pp A `ppp` object, or a list of `ppp` objects.
#' @param method One of `"uniform"`, `"kde"`, `"window"`.
#' @param n_target Number of points to keep. Mutually exclusive with `prop`.
#'   With a list, either one value or one value per pattern.
#' @param prop Fraction of points to keep, in (0, 1]. Mutually exclusive with
#'   `n_target`.
#' @param marks Optional character vector of cell types (mark levels) to
#'   keep; the other points are dropped before downsampling.
#' @param by_marks If `TRUE`, each cell type is downsampled separately and
#'   `n_target` / `prop` apply to each type (e.g. `n_target = 40000` keeps
#'   up to 40000 cells *of each type*). Types with fewer points are kept
#'   whole. With `method = "uniform"` this is still independent thinning, so
#'   cross-type K and L functions are unchanged. Not available for
#'   `method = "window"`.
#' @param ... Further arguments passed to the method function.
#'
#' @return A `ppp` (or a list of `ppp`, with the input names) with attribute
#'   `"downsample"` describing the operation.
#' @export
#' @examples
#' library(spatstat.random)
#' set.seed(1)
#' X <- rpoispp(2000)
#' Y <- downsample(X, method = "uniform", prop = 0.1)
#' attr(Y, "downsample")
#'
#' # several samples, in parallel
#' # future::plan(future::multisession, workers = 4)
#' Xs <- list(a = rpoispp(2000), b = rpoispp(3000))
#' Ys <- downsample(Xs, method = "window", n_target = 500)
#' sapply(Ys, spatstat.geom::npoints)
downsample <- function(pp, method = c("uniform", "kde", "window"),
                       n_target = NULL, prop = NULL,
                       marks = NULL, by_marks = FALSE, ...) {
  method <- match.arg(method)
  fun <- switch(method,
                uniform = downsample_uniform,
                kde     = downsample_KDE,
                window  = downsample_window)
  if (by_marks && method == "window") {
    stop("`by_marks = TRUE` is not available for method \"window\": ",
         "each cell type would get a different window.", call. = FALSE)
  }
  one <- function(x, n_target, prop) {
    .downsample_marks(x, fun, method, n_target, prop, marks, by_marks, ...)
  }

  if (spatstat.geom::is.ppp(pp)) {
    return(one(pp, n_target, prop))
  }

  if (!is.list(pp) || !all(vapply(pp, spatstat.geom::is.ppp, logical(1)))) {
    stop("`pp` must be a ppp object or a list of ppp objects.", call. = FALSE)
  }
  n <- length(pp)
  n_target <- .recycle_arg(n_target, n, "n_target")
  prop     <- .recycle_arg(prop, n, "prop")

  out <- future.apply::future_lapply(
    seq_len(n),
    function(k) one(pp[[k]], n_target[[k]], prop[[k]]),
    future.seed = TRUE
  )
  names(out) <- names(pp)
  out
}
