# WARNING - Generated by {fusen} from dev/flat_downsampling.qmd: do not edit by hand # nolint: line_length_linter.

#' Downsampling by sub-windows
#'
#' Divides the window into a grid of square tiles and adds randomly chosen
#' tiles until at least `n_target` points are covered. All points inside the
#' chosen tiles are kept, and the window of the result is the union of those
#' tiles intersected with the original window, so edge corrections in
#' `Lcross` stay correct.
#'
#' Local structure is fully preserved, but the observed area shrinks: border
#' effects grow and the largest usable distance `r` gets smaller (at most
#' about `tile_size / 2` for an isolated tile).
#'
#' @inheritParams downsample
#' @param tile_size Side of the square tiles, in the units of `pp`. Default:
#'   the side giving about 100 tiles over the bounding box.
#' @param weighted If `TRUE`, tiles are drawn with probability proportional
#'   to the number of points they contain (fewer empty tiles). Default
#'   `FALSE`, i.e. uniform over non-empty tiles.
#'
#' @return A `ppp` with attribute `"downsample"`; its element `tiles` is the
#'   `tess` of the chosen tiles.
#' @export
#' @examples
#' library(spatstat.random)
#' set.seed(1)
#' X <- rpoispp(2000)
#' Y <- downsample_window(X, prop = 0.25)
#' plot(Y)
downsample_window <- function(pp, n_target = NULL, prop = NULL,
                              tile_size = NULL, weighted = FALSE) {
  .check_ppp(pp)
  n <- spatstat.geom::npoints(pp)
  tgt <- .resolve_target(n, n_target, prop)
  if (tgt >= n) return(.tag(pp, "window", n))

  W <- spatstat.geom::Window(pp)
  bb <- spatstat.geom::Frame(pp)
  if (is.null(tile_size)) {
    tile_size <- sqrt(spatstat.geom::area(bb) / 100)
  }
  stopifnot(is.numeric(tile_size), length(tile_size) == 1, tile_size > 0)

  xb <- seq(bb$xrange[1], bb$xrange[2] + tile_size, by = tile_size)
  yb <- seq(bb$yrange[1], bb$yrange[2] + tile_size, by = tile_size)
  ix <- findInterval(pp$x, xb, rightmost.closed = TRUE)
  iy <- findInterval(pp$y, yb, rightmost.closed = TRUE)
  tile_id <- paste(ix, iy, sep = "_")

  counts <- table(tile_id)
  ids <- names(counts)
  prob <- if (weighted) as.numeric(counts) else NULL
  ord <- if (length(ids) > 1) {
    sample(ids, length(ids), prob = prob)
  } else {
    ids
  }
  k <- which(cumsum(as.numeric(counts[ord])) >= tgt)[1]
  chosen <- ord[seq_len(k)]

  ij <- do.call(rbind, strsplit(chosen, "_", fixed = TRUE))
  ij <- matrix(as.integer(ij), ncol = 2)
  tiles <- lapply(seq_len(nrow(ij)), function(r) {
    spatstat.geom::owin(xb[ij[r, 1] + 0:1], yb[ij[r, 2] + 0:1])
  })
  Wnew <- spatstat.geom::intersect.owin(
    W, do.call(spatstat.geom::union.owin, tiles)
  )

  keep <- tile_id %in% chosen
  out <- pp[keep]
  spatstat.geom::Window(out) <- Wnew
  .tag(out, "window", n, tile_size = tile_size,
       tiles = spatstat.geom::tess(tiles = tiles))
}
