# WARNING - Generated by {fusen} from dev/flat_read_data.qmd: do not edit by hand # nolint: line_length_linter.

#' Read cell centroids and labels from an h5ad file
#'
#' Reads an AnnData file (`.h5ad`, optionally gzip-compressed `.h5ad.gz`)
#' and returns one row per cell with its coordinates and its label (for
#' example the cell type). Requires the Bioconductor package `anndataR`.
#'
#' @param data_path Path to the `.h5ad` or `.h5ad.gz` file.
#' @param marks_col Name of the `obs` column with the cell labels, or `NULL`
#'   to read coordinates only.
#' @param spatial_key Name of the `obsm` matrix with the coordinates (first
#'   column x, second column y). Ignored if `coords_cols` is given.
#' @param coords_cols Optional: names of two `obs` columns holding x and y,
#'   to use instead of `obsm[[spatial_key]]`.
#'
#' @return A `data.frame` with columns `x`, `y` and, if `marks_col` is not
#'   `NULL`, `mark` (a factor). Row names are the cell ids (`obs_names`).
#' @export
#' @examples
#' f <- system.file("extdata", "tcga_tiny.h5ad", package = "SpaFun")
#' if (nzchar(f) && requireNamespace("anndataR", quietly = TRUE)) {
#'   cells <- read_cells_h5ad(f, marks_col = "type")
#'   head(cells)
#'   table(cells$mark)
#' }
read_cells_h5ad <- function(data_path, marks_col = "type",
                            spatial_key = "spatial", coords_cols = NULL) {
  if (!requireNamespace("anndataR", quietly = TRUE)) {
    stop("Package 'anndataR' is needed to read h5ad files. Install it with ",
         "BiocManager::install(\"anndataR\").", call. = FALSE)
  }
  if (!is.character(data_path) || length(data_path) != 1 ||
      !file.exists(data_path)) {
    stop("`data_path` must be the path of an existing file.", call. = FALSE)
  }

  # decompress only if the file really is gzip: some ".h5ad.gz" files are
  # plain HDF5 with a misleading extension
  if (.is_gzip(data_path)) {
    tmp <- .gunzip_tmp(data_path)
    on.exit(unlink(tmp), add = TRUE)
    data_path <- tmp
  }
  ann <- anndataR::read_h5ad(data_path)
  obs <- as.data.frame(ann$obs)

  # coordinates
  if (!is.null(coords_cols)) {
    if (length(coords_cols) != 2 || !all(coords_cols %in% names(obs))) {
      stop("`coords_cols` must be two column names of obs. Available: ",
           paste(names(obs), collapse = ", "), call. = FALSE)
    }
    xy <- cbind(obs[[coords_cols[1]]], obs[[coords_cols[2]]])
  } else {
    obsm <- ann$obsm
    if (is.null(obsm) || !spatial_key %in% names(obsm)) {
      stop("obsm has no matrix called '", spatial_key, "'. Available: ",
           paste(names(obsm), collapse = ", "),
           ". Set `spatial_key` or `coords_cols`.", call. = FALSE)
    }
    xy <- as.matrix(obsm[[spatial_key]])
    if (ncol(xy) < 2) {
      stop("obsm[['", spatial_key, "']] must have at least 2 columns.",
           call. = FALSE)
    }
  }

  cells <- data.frame(x = as.numeric(xy[, 1]), y = as.numeric(xy[, 2]))

  # labels
  if (!is.null(marks_col)) {
    if (!marks_col %in% names(obs)) {
      stop("Column '", marks_col, "' not found in obs. Available: ",
           paste(names(obs), collapse = ", "), call. = FALSE)
    }
    cells$mark <- as.factor(obs[[marks_col]])
  }

  ids <- tryCatch(ann$obs_names, error = function(e) NULL)
  if (length(ids) == nrow(cells)) rownames(cells) <- ids
  cells
}
