# WARNING - Generated by {fusen} from dev/flat_read_data.qmd: do not edit by hand # nolint: line_length_linter.

#' Internal helpers for reading data
#' @noRd
.resolve_mask_scale <- function(mask, mask_scale, magnif, thumb_mag) {
  if (!is.null(mask_scale) && !is.null(magnif)) {
    stop("Give either `mask_scale` or `magnif`, not both.", call. = FALSE)
  }
  if (!is.null(magnif)) {
    if (!is.numeric(magnif) || length(magnif) != 1 || magnif <= 0 ||
        !is.numeric(thumb_mag) || length(thumb_mag) != 1 || thumb_mag <= 0) {
      stop("`magnif` and `thumb_mag` must be single positive numbers ",
           "(e.g. 40, not \"40x\").", call. = FALSE)
    }
    mask_scale <- magnif / thumb_mag
  }
  if (!is.null(mask_scale) &&
      (!is.numeric(mask_scale) || length(mask_scale) != 1 || mask_scale <= 0)) {
    stop("`mask_scale` must be a single positive number.", call. = FALSE)
  }
  if (is.character(mask) && is.null(mask_scale)) {
    stop("With a PNG mask, give `mask_scale` or `magnif` (and `thumb_mag`).",
         call. = FALSE)
  }
  mask_scale
}

.png2owin <- function(path, scale, threshold = 0.5, invert = FALSE) {
  if (!file.exists(path)) {
    stop("Mask file not found: ", path, call. = FALSE)
  }
  img <- png::readPNG(path)
  # grey levels: average of the colour channels, alpha channel ignored
  if (length(dim(img)) == 3) {
    nch <- dim(img)[3]
    col_ch <- if (nch %in% c(2, 4)) seq_len(nch - 1) else seq_len(nch)
    img <- apply(img[, , col_ch, drop = FALSE], c(1, 2), mean)
  }
  m <- if (invert) img < threshold else img > threshold
  if (!any(m)) {
    stop("The mask is empty: no pixel above `threshold`. ",
         "Check `threshold` or `invert`.", call. = FALSE)
  }
  # readPNG: rows = y (top row first), columns = x. owin masks use the same
  # layout (row i = i-th y value), so no transpose is needed.
  spatstat.geom::owin(xrange = c(0, ncol(m) * scale),
                      yrange = c(0, nrow(m) * scale),
                      mask = m)
}

.is_gzip <- function(path) {
  con <- file(path, "rb")
  on.exit(close(con))
  magic <- readBin(con, "raw", n = 2)
  length(magic) == 2 && magic[1] == as.raw(0x1f) && magic[2] == as.raw(0x8b)
}

.gunzip_tmp <- function(path) {
  tmp <- tempfile(fileext = ".h5ad")
  con_in <- gzfile(path, "rb")
  on.exit(close(con_in))
  con_out <- file(tmp, "wb")
  on.exit(close(con_out), add = TRUE)
  repeat {
    buf <- readBin(con_in, "raw", n = 1e7)
    if (length(buf) == 0) break
    writeBin(buf, con_out)
  }
  tmp
}
